In [1]:
import numpy as np
import matplotlib.pyplot as plt
import cv2
import os

In [2]:
!rm -rf animals10small.zip animals10small
!gdown -q 1Do8SXKm4rmXW-phHlejV-udLfhSyYgKk -O animals10small.zip
!unzip -qq animals10small.zip

# Exercise-1

In [14]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report

# 1. Load dataset
iris = load_iris()
X = iris.data
y = iris.target

print("Dataset info: ")
print("Whole dataset; X.shape: ", X.shape)
print("Whole dataset; y.shape: ", y.shape)
print("="*100); print()


# 2. Split data into train/test
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print("Train/Test set: ")
print("Train dataset; X_train.shape, y_train.shape: ", X_train.shape, y_train.shape)
print("Test dataset; X_test.shape, y_test.shape: ", X_test.shape, y_test.shape)
print("="*100); print()

# 3. Create MLP classifier
model = MLPClassifier(
    hidden_layer_sizes=(16, 8),
    activation='relu',
    solver='adam',
    max_iter=500,
    random_state=42
)

# 4. Train model
model.fit(X_train, y_train)

# 5. Predict
y_pred = model.predict(X_test)

# 6. Evaluation
print(classification_report(y_test, y_pred, target_names=iris.target_names))

Dataset info: 
Whole dataset; X.shape:  (150, 4)
Whole dataset; y.shape:  (150,)

Train/Test set: 
Train dataset; X_train.shape, y_train.shape:  (120, 4) (120,)
Test dataset; X_test.shape, y_test.shape:  (30, 4) (30,)

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00        10
   virginica       1.00      1.00      1.00        10

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(


In [5]:
blob = load_iris()
blob.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [12]:
blob.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [8]:
X[:5], y[:5]

(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2]]),
 array([0, 0, 0, 0, 0]))

In [11]:
X[-5:], y[-5:]

(array([[6.7, 3. , 5.2, 2.3],
        [6.3, 2.5, 5. , 1.9],
        [6.5, 3. , 5.2, 2. ],
        [6.2, 3.4, 5.4, 2.3],
        [5.9, 3. , 5.1, 1.8]]),
 array([2, 2, 2, 2, 2]))

In [13]:
blob.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

## Model's parameters

In [17]:
print(type(model.coefs_))
print(len(model.coefs_))


<class 'list'>
3


In [18]:
for w in model.coefs_:
  print(w.shape)

(4, 16)
(16, 8)
(8, 3)


In [20]:
print(type(model.intercepts_))
print(len(model.intercepts_))
for b in model.intercepts_:
  print(b.shape)

<class 'list'>
3
(16,)
(8,)
(3,)


## define your own predict

In [37]:
def relu(x):
  x[x<0] = 0
  return x

def softmax(Z, axis=-1):
  Max = Z.max(axis=axis, keepdims=True)
  ZM = Z - Max
  EZM = np.exp(ZM)
  EZM_sum = EZM.sum(axis=axis, keepdims=True)
  return EZM / EZM_sum


In [38]:
def predict(X, w:list=model.coefs_, b:list=model.intercepts_):
  Z = X
  for w, b in zip(w, b):
    Z = relu(Z @ w + b)
  z = softmax(Z)
  return np.argmax(z, axis=-1)

In [40]:
model_predict = model.predict(X_test)
your_predict = predict(X_test, model.coefs_, model.intercepts_)
print("model_predict: "); print(model_predict[:5])
print("your_predict: "); print(your_predict[:5])
print("check the equility: ", np.all(model_predict==model_predict))

model_predict: 
[0 2 1 1 0]
your_predict: 
[0 2 1 1 0]
check the equility:  True
